POST localhost:3002/barang/kategori
Content-Type: application/json
Accept: application/json

{
  "nama_kategori_barang" : "obat jamu test"
}

###

POST localhost:3002/barang/kategori
Content-Type: application/json
Accept: application/json

{
  "nama_kategori_barang" : "obat kencur"
}

###

POST localhost:3002/barang/kategori
Content-Type: application/json
Accept: application/json

{
  "nama_kategori_barang" : "obat jahe"
}

###

GET localhost:3002/barang/kategori
Accept: application/json

###

GET localhost:3002/barang/kategori/3
Accept: application/json

###

PUT localhost:3003/barang/kategori/9
Content-Type: application/json
Accept: application/json
Authorization: abc123

{
  "nama_kategori_barang" : "obat kontol iblis"
}

###

DELETE localhost:3002/barang/kategori/4