POST localhost:3002/barang/
Content-Type: application/json
Accept: application/json

{
  "kategori_barang" : [1,2,3],
  "data_barang" : {
    "nama_barang" : "alat kecantikan 1000",
    "harga" : 50000.0,
    "deskripsi" : "alat kecatikan auto cantik"
  }
}

###

PUT localhost:3002/barang/1
Content-Type: application/json
Accept: application/json

{
  "nama_barang" : "alat kecantikan 1000 oryza p!nk",
  "harga" : 1250000.0,
  "deskripsi" : "alat kecatikan auto cantik forever"
}

###

GET localhost:3002/barang/

###

GET localhost:3002/barang/2

###

DELETE localhost:3002/barang/2